"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SearchRequestDetails(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    USER_AGENT_FIELD_NUMBER: builtins.int
    USER_IP_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    NUM_RESULTS_FIELD_NUMBER: builtins.int
    application_id: typing.Text
    user_agent: typing.Text
    user_ip: typing.Text
    status: builtins.int
    num_results: builtins.int
    def __init__(self,
        *,
        application_id: typing.Text = ...,
        user_agent: typing.Text = ...,
        user_ip: typing.Text = ...,
        status: builtins.int = ...,
        num_results: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["application_id",b"application_id","num_results",b"num_results","status",b"status","user_agent",b"user_agent","user_ip",b"user_ip"]) -> None: ...
global___SearchRequestDetails = SearchRequestDetails
