# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acoustid_stats/acoustid_stats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#acoustid_stats/acoustid_stats.proto\x1a\x1bgoogle/protobuf/empty.proto\"x\n\x14SearchRequestDetails\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x12\n\nuser_agent\x18\x02 \x01(\t\x12\x0f\n\x07user_ip\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x05\x12\x13\n\x0bnum_results\x18\x05 \x01(\x05\x32Y\n\x15\x41\x63oustidRealTimeStats\x12@\n\x0fOnSearchRequest\x12\x15.SearchRequestDetails\x1a\x16.google.protobuf.Emptyb\x06proto3')



_SEARCHREQUESTDETAILS = DESCRIPTOR.message_types_by_name['SearchRequestDetails']
SearchRequestDetails = _reflection.GeneratedProtocolMessageType('SearchRequestDetails', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUESTDETAILS,
  '__module__' : 'acoustid_stats.acoustid_stats_pb2'
  # @@protoc_insertion_point(class_scope:SearchRequestDetails)
  })
_sym_db.RegisterMessage(SearchRequestDetails)

_ACOUSTIDREALTIMESTATS = DESCRIPTOR.services_by_name['AcoustidRealTimeStats']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHREQUESTDETAILS._serialized_start=68
  _SEARCHREQUESTDETAILS._serialized_end=188
  _ACOUSTIDREALTIMESTATS._serialized_start=190
  _ACOUSTIDREALTIMESTATS._serialized_end=279
# @@protoc_insertion_point(module_scope)
