# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from acoustid_stats import acoustid_stats_pb2 as acoustid__stats_dot_acoustid__stats__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AcoustidRealTimeStatsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnSearchRequest = channel.unary_unary(
                '/AcoustidRealTimeStats/OnSearchRequest',
                request_serializer=acoustid__stats_dot_acoustid__stats__pb2.SearchRequestDetails.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AcoustidRealTimeStatsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnSearchRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcoustidRealTimeStatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnSearchRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSearchRequest,
                    request_deserializer=acoustid__stats_dot_acoustid__stats__pb2.SearchRequestDetails.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AcoustidRealTimeStats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AcoustidRealTimeStats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnSearchRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AcoustidRealTimeStats/OnSearchRequest',
            acoustid__stats_dot_acoustid__stats__pb2.SearchRequestDetails.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
